Repository UniOfGreenwich/elee1149-coursework--steak, pull requests merged in 2025-03, with the labels that each got.

#125 Doc/requirements
  Docs/System Modelling/Activity_Diagrams.md
  Docs/System Modelling/Sequence_Diagrams.md
Labels: documentation

#126 Doc/unit test 5
  Docs/Unit Tests/Test_5_Accounts_Budgeting.md
  steakinc-web-app/steakinc-web-app/python_backend/test_accounts_budget_functionality.py
Labels: Testing

#129 Feature/us0029 qa fixes
  Docs/Sprint Planning/Sprint_Planning7.md
  steakinc-web-app/steakinc-web-app/python_backend/app.py
  steakinc-web-app/steakinc-web-app/src/AccountInfoScreen/AccountInfoScreen.jsx
  steakinc-web-app/steakinc-web-app/src/ForgotPasswordScreen/ForgotPasswordScreen.jsx
  steakinc-web-app/steakinc-web-app/src/LoginScreen/LoginScreen.jsx
  steakinc-web-app/steakinc-web-app/src/RegisterScreen/RegisterScreen.jsx
Labels: enhancement

#127 Doc/stand up documents
  Docs/Standup Notes/Stand_Up_03032025.md
  Docs/Standup Notes/Stand_Up_26022025.md
  Docs/Standup Notes/Stand_Up_28022025.md
Labels: documentation

#135 Account styling
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.css
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.jsx
  steakinc-web-app/steakinc-web-app/src/AccountScreen/HorizontalCarouselAccounts.css
  steakinc-web-app/steakinc-web-app/src/AccountScreen/HorizontalCarouselAccounts.jsx
  steakinc-web-app/steakinc-web-app/src/AccountScreen/VerticalCarouselAccounts.css
  steakinc-web-app/steakinc-web-app/src/AccountScreen/VerticalCarouselAccounts.jsx
  steakinc-web-app/steakinc-web-app/src/AccountScreen/useWindowDimensions.js
Labels: enhancement

#144 Added all functionality to dashboard
  steakinc-web-app/steakinc-web-app/python_backend/app.py
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.jsx
  steakinc-web-app/steakinc-web-app/src/DashboardScreen/DashboardScreen.jsx
  steakinc-web-app/steakinc-web-app/src/TransactionScreen/TransactionScreen.jsx
  steakinc-web-app/steakinc-web-app/src/components/TransactionsChart.jsx
  steakinc-web-app/steakinc-web-app/src/components/TransactionsTable.css
  steakinc-web-app/steakinc-web-app/src/components/TransactionsTable.jsx
Labels: enhancement

#145 Updated Regex for password verification
  steakinc-web-app/steakinc-web-app/src/RegisterScreen/RegisterScreen.jsx
Labels: bug

#136 Doc/sprint documents
  Docs/Sprint Planning/Sprint_Planning8.md
  Docs/Sprint Planning/Sprint_Review6.md
  Docs/Sprint Planning/Sprint_Review7.md
Labels: documentation

#147 Doc/stand up documents
  Docs/Standup Notes/Stand_Up_06032025.md
  Docs/Standup Notes/Stand_Up_10032025.md
Labels: documentation

#150 Doc/stand up documents
  Docs/Standup Notes/Stand_Up_12032025
  Docs/Standup Notes/Stand_Up_17032025.md
Labels: documentation

#154 Update deploy.yaml
  .github/workflows/deploy.yaml
Labels: enhancement

#155 Update deploy.yaml
  .github/workflows/deploy.yaml
Labels: enhancement

#160 https secure
  steakinc-web-app/steakinc-web-app/src/AccountInfoScreen/AccountInfoScreen.jsx
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.jsx
  steakinc-web-app/steakinc-web-app/src/BudgetScreen/BudgetScreen.jsx
  steakinc-web-app/steakinc-web-app/src/DashboardScreen/DashboardScreen.jsx
  steakinc-web-app/steakinc-web-app/src/ForgotPasswordScreen/ForgotPasswordScreen.jsx
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
  steakinc-web-app/steakinc-web-app/src/LoginScreen/LoginScreen.jsx
  steakinc-web-app/steakinc-web-app/src/RegisterScreen/RegisterScreen.jsx
  steakinc-web-app/steakinc-web-app/src/TransactionScreen/TransactionScreen.jsx
  steakinc-web-app/steakinc-web-app/src/components/TransactionForm.jsx
Labels: enhancement

#161 Develop
  steakinc-web-app/steakinc-web-app/src/AccountInfoScreen/AccountInfoScreen.jsx
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.jsx
  steakinc-web-app/steakinc-web-app/src/BudgetScreen/BudgetScreen.jsx
  steakinc-web-app/steakinc-web-app/src/DashboardScreen/DashboardScreen.jsx
  steakinc-web-app/steakinc-web-app/src/ForgotPasswordScreen/ForgotPasswordScreen.jsx
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
  steakinc-web-app/steakinc-web-app/src/LoginScreen/LoginScreen.jsx
  steakinc-web-app/steakinc-web-app/src/RegisterScreen/RegisterScreen.jsx
  steakinc-web-app/steakinc-web-app/src/TransactionScreen/TransactionScreen.jsx
  steakinc-web-app/steakinc-web-app/src/components/TransactionForm.jsx
Labels: enhancement

#163 Update HomeScreen.jsx
  steakinc-web-app/steakinc-web-app/src/HomeScreen/HomeScreen.jsx
Labels: bug

#164 Develop
  steakinc-web-app/steakinc-web-app/src/ForgotPasswordScreen/ForgotPasswordScreen.jsx
  steakinc-web-app/steakinc-web-app/src/HomeScreen/HomeScreen.jsx
  steakinc-web-app/steakinc-web-app/src/JarsScreen/NavSideBar.jsx
  steakinc-web-app/steakinc-web-app/src/LoginScreen/LoginScreen.jsx
  steakinc-web-app/steakinc-web-app/src/RegisterScreen/RegisterScreen.jsx
Labels: bug

#165 Update DashboardScreen.jsx
  steakinc-web-app/steakinc-web-app/src/DashboardScreen/DashboardScreen.jsx
Labels: bug

#166 Update JarsScreen.jsx
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
Labels: enhancement

#167 Develop
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
Labels: bug

#169 Develop
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
Labels: bug

#170 Update JarsScreen.jsx
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
Labels: bug

#180 Relevant changes made for gh pages
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.jsx
  steakinc-web-app/steakinc-web-app/src/HomeScreen/Carousel.css
  steakinc-web-app/steakinc-web-app/src/HomeScreen/HomeScreen.css
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
  steakinc-web-app/steakinc-web-app/src/TransactionScreen/TransactionScreen.jsx
  steakinc-web-app/steakinc-web-app/src/components/TransactionForm.jsx
Labels: bug

#181 Develop
  steakinc-web-app/steakinc-web-app/src/AccountScreen/AccountScreen.jsx
  steakinc-web-app/steakinc-web-app/src/HomeScreen/Carousel.css
  steakinc-web-app/steakinc-web-app/src/HomeScreen/HomeScreen.css
  steakinc-web-app/steakinc-web-app/src/JarsScreen/JarsScreen.jsx
  steakinc-web-app/steakinc-web-app/src/TransactionScreen/TransactionScreen.jsx
  steakinc-web-app/steakinc-web-app/src/components/TransactionForm.jsx
Labels: bug
